import 'package:flutter/material.dart';

void main() {
  runApp(const RegisterPage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class RegisterPage extends StatelessWidget {
  const RegisterPage({super.key});
  static const nameRoute = '/register';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(),
      home: Scaffold(
        appBar: PreferredSize(
            preferredSize: Size.fromHeight(kToolbarHeight + 50),
            child: Container(
              decoration:
                  BoxDecoration(borderRadius: BorderRadius.circular(20)),
              child: Stack(
                children: [
                  Container(
                    child: Positioned(
                      top: 30,
                      left: 20,
                      child: FloatingActionButton(
                        onPressed: () {
                          Navigator.of(context).pop();
                        },
                        child: const Icon(Icons.arrow_back),
                      ),
                    ),
                  )
                ],
              ),
            )),
        body: ListView(padding: EdgeInsets.fromLTRB(20, 0, 20, 0), children: [
          FormRegister(),
        ]),
      ),
    );
  }
}

class FormRegister extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Container(
            width: MediaQuery.of(context).size.width * 0.3,
            height: MediaQuery.of(context).size.height * 0.4,
            child: Image(
              image: AssetImage('rb_2150923186.png'),
              fit: BoxFit.contain,
            )),
        Container(
            margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
            height: 55,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: Colors.white),
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "biawak@gmail.com",
                  labelText: "Username",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),
        Container(
            margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
            height: 55,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: Colors.white),
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "Acang Bin Atang",
                  labelText: "Username",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),
        Container(
            margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
            height: 55,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: Colors.white),
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "biawak@gmail.com",
                  labelText: "Email",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),
        Container(
            margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
            height: 55,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: Colors.white),
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  labelText: "Password",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),
        Container(
            margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
            height: 55,
            clipBehavior: Clip.antiAlias,
            decoration: BoxDecoration(color: Colors.white),
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  labelText: "Rewrite Password",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),
      ],
    );
  }
}

const authOutlineInputBorder = OutlineInputBorder(
  borderSide: BorderSide(color: Color(0xFF214C7A)),
  borderRadius: BorderRadius.all(Radius.circular(15)),
);
