import 'package:flutter/material.dart';

void main() {
  runApp(const Register());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Register extends StatelessWidget {
  const Register({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(),
      home: Scaffold(
        body: ListView(
          padding: EdgeInsets.fromLTRB(20, 0, 20, 0),
          children: [Register(),]),
      ),
    );
  }
}

class Coba extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
        margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
        height: 55,
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(color: Colors.white),
        child: Container(
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "biawak@gmail.com",
                  labelText: "Username",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),       
        ),
                Container(
                          margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
        height: 55,
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(color: Colors.white),
        child: Container(
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "Acang Bin Atang",
                  labelText: "Username",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),       
        ),
                Container(
                          margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
        height: 55,
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(color: Colors.white),
        child: Container(
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  hintText: "biawak@gmail.com",
                  labelText: "Email",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),       
        ),
                Container(
                          margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
        height: 55,
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(color: Colors.white),
        child: Container(
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  labelText: "Password",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),       
        ),
        Container(
                          margin: EdgeInsets.fromLTRB(0, 32, 0, 0),
        height: 55,
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(color: Colors.white),
        child: Container(
            child: TextFormField(
                onSaved: (password) {},
                onChanged: (password) {},
                obscureText: true,
                decoration: InputDecoration(
                  labelText: "Rewrite Password",
                  floatingLabelBehavior: FloatingLabelBehavior.never,
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 16,
                  ),
                  border: authOutlineInputBorder,
                  enabledBorder: authOutlineInputBorder,
                  focusedBorder: authOutlineInputBorder.copyWith(
                      borderSide: const BorderSide(color: Color(0xFF214C7A))),
                ))),       
        )
      ],
    );
  }
}

const authOutlineInputBorder = OutlineInputBorder(
  borderSide: BorderSide(color: Color(0xFF214C7A)),
  borderRadius: BorderRadius.all(Radius.circular(15)),
);
